repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=20000"]

  - repo: https://github.com/avilaton/add-msg-issue-prefix-hook
    rev: v0.0.9
    hooks:
      - id: add-msg-issue-prefix
        args:
          - "--template={}: "

  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
